# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Woosik
tagline:          'A Jekyll theme'
description:      Deep learning, Data Analysis
url:              https://woosikyang.github.io
baseurl:          ""

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

  gems  :
  - jekyll-paginate
paginate: 10